image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./mvnw -Dquickly
  - name: Set Kubeconfig
    command: echo $K8S_CTX | base64 -d > ~/.kube/config
  - name: Quarkus command
    openMode: split-right

vscode:
  extensions:
    - "redhat.java"
    - "vscjava.vscode-java-dependency"
    - "vscjava.vscode-java-debug"
    - "vscjava.vscode-java-pack"    